name: Sync demo to template repo

on:
  push:
    branches:
      - main
      - beta
    paths:
      - 'demo/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup git identity
        run: |
          git config user.name "0-Sandy"
          git config user.email "github@sandy00.aleeas.com"

      - name: Create subtree branch
        run: |
          git subtree split --prefix=demo -b demo-branch
      
      - name: Update README link
        run: |
          git checkout demo-branch

          sed -i 's|> Better Invite Starter code is also available on a separate \[repository\](https://github.com/better-invite/better-invite-starter/tree/main)|> Better Invite Starter code is also available on the \[Better Invite monorepo\](https://github.com/better-invite/better-invite/tree/main/demo)|' README.md

          git add README.md

      - name: Add FUNDING.yml
        run: |
          mkdir -p .github
          echo "patreon: betterinvite" > .github/FUNDING.yml

          git add .github/FUNDING.yml

      - name: Add CODEOWNERS
        run: |
          mkdir -p .github
          printf "# https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners\n\n* @0-Sandy\n" > .github/CODEOWNERS

          git add .github/CODEOWNERS
          git commit --amend --no-edit
      - name: Apply modifications
        run: |
          git checkout demo-branch

          # Update README
          sed -i 's|> Better Invite Starter code is also available on a separate \[repository\](https://github.com/better-invite/better-invite-starter/tree/main)|> Better Invite Starter code is also available on the \[Better Invite monorepo\](https://github.com/better-invite/better-invite/tree/main/demo)|' README.md

          # Create .github files
          mkdir -p .github

          echo "patreon: betterinvite" > .github/FUNDING.yml

          printf "# https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners\n\n* @0-Sandy" > .github/CODEOWNERS

          # Commit changes
          git add .
          git commit --amend --no-edit

      - name: Push to template repo
        run: |
          git remote add template https://x-access-token:${{ secrets.TEMPLATE_REPO_TOKEN }}@github.com/better-invite/better-invite-starter.git
          git push template demo-branch:${{ github.ref_name }} --force